import type { NextPage } from 'next'
import { GetServerSideProps } from 'next';
import { useRouter } from 'next/router';
import { Hero, Main, Footer } from '../components'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavLink from '../components/NavLink'
import firebase from 'firebase/app';
import 'firebase/storage';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='CONNEQT' message='Professional Connections Made Easy.' />
      <Main />
      <Footer /> 
    </>
  )
}

export default Home
